### ISSUE TITLE
wild ignore?

### ISSUE THREAD

**Issue by cj** [nhmood/watson-ruby#122] opened 2013-11-25 18:09 UTC
It seems like wild ignore doesn't work.  I added `*.swo` under `[ignore]` but it still showing files with that extension, am I missing something?

**Comment by nhmood** [comment] 2013-11-25 23:48
I can confirm the wild ignore in the config isn't working right now. I'll take a look at it, I think I might be doing something wrong with the regex. 
The `-i` on the command line seems to be working though in case you need to ignore things.

**Comment by nhmood** [comment] 2013-11-26 07:35
Fixed with b34ec090403983775fda01b5ac259994ee7e1b42 and latest gem release (v1.1.1)

The config parser regex was lazily copied from the tag and dir sections so it didn't account for *.type wildcards :[, it should pick those up now though!

**Closed as completed by nhmood** 2013-11-26 07:35 UTC
